# Generated by Django 3.2.7 on 2021-10-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('course', models.IntegerField(verbose_name='科目')),
                ('title', models.TextField(verbose_name='题目')),
                ('a', models.CharField(max_length=40, verbose_name='A选项')),
                ('b', models.CharField(max_length=40, verbose_name='B选项')),
                ('c', models.CharField(max_length=40, verbose_name='C选项')),
                ('d', models.CharField(max_length=40, verbose_name='D选项')),
                ('answer', models.CharField(default='', max_length=1000, verbose_name='答案')),
                ('difficulty', models.CharField(default='一般', max_length=10, verbose_name='难度')),
                ('score', models.IntegerField(verbose_name='分值')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('xuehao', models.IntegerField(verbose_name='学号')),
                ('grade', models.FloatField(verbose_name='成绩')),
                ('test_paper_id', models.IntegerField(verbose_name='试卷ID')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='题目')),
                ('owner', models.CharField(default='', max_length=100, verbose_name='出卷人')),
                ('course', models.CharField(default='', max_length=100, verbose_name='科目')),
                ('time', models.IntegerField(help_text='单位是分钟', verbose_name='考试时长')),
                ('exam_time', models.DateTimeField(auto_now_add=True, verbose_name='考试时间')),
                ('pid', models.ManyToManyField(to='cms.Question')),
            ],
            options={
                'db_table': 'test_paper',
            },
        ),
    ]
