# Generated by Django 3.2.7 on 2021-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
