# Generated by Django 3.2.7 on 2021-10-24 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_record_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='exam_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='考试时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='exam_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='出卷时间'),
        ),
    ]
