# Generated by Django 3.2.7 on 2021-10-30 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20211024_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_modify_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='最后更新时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.CharField(default='admin', max_length=20, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='单选题', max_length=10, verbose_name='试题类型'),
        ),
    ]
