# Generated by Django 3.2.7 on 2021-10-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20211030_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpaper',
            name='pid',
        ),
        migrations.AddField(
            model_name='testpaper',
            name='pid',
            field=models.CharField(default='', max_length=500, verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='title',
            field=models.CharField(max_length=40, unique=True, verbose_name='试卷名称'),
        ),
    ]
