# Generated by Django 3.2.7 on 2021-10-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20211030_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a',
            field=models.CharField(max_length=40, null=True, verbose_name='A选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='b',
            field=models.CharField(max_length=40, null=True, verbose_name='B选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='c',
            field=models.CharField(max_length=40, null=True, verbose_name='C选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.IntegerField(null=True, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.CharField(max_length=40, null=True, verbose_name='D选项'),
        ),
    ]
