# Generated by Django 3.2.7 on 2021-10-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20211030_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='answer',
            field=models.CharField(default='', max_length=500, verbose_name='答案'),
        ),
    ]
