# Generated by Django 3.2.7 on 2021-10-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_testpaper_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='answer',
            field=models.CharField(default='', max_length=500, verbose_name='考生答案'),
        ),
    ]
