# Generated by Django 3.2.7 on 2021-10-24 01:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(default='', max_length=100, verbose_name='学号')),
                ('name', models.CharField(default='', max_length=100, verbose_name='姓名')),
                ('password', models.CharField(default='', max_length=100, verbose_name='密码')),
                ('gender', models.CharField(default='', max_length=100, verbose_name='性别')),
                ('phone', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='电话号码')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('image', models.CharField(default='/static/image/default.png', max_length=200, verbose_name='头像')),
                ('role', models.IntegerField(default=1, verbose_name='角色')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='', max_length=20, verbose_name='科目名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('password', models.CharField(default='123', max_length=50, verbose_name='密码')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='手机号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('role', models.IntegerField(default=3, verbose_name='角色')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20, verbose_name='老师姓名')),
                ('number', models.CharField(default='', max_length=100, verbose_name='工号')),
                ('password', models.CharField(default='', max_length=100, verbose_name='密码')),
                ('phone', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='电话号码')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('teacher_school', models.CharField(default='', max_length=100, verbose_name='老师所在学校')),
                ('role', models.IntegerField(default=2, verbose_name='角色')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subject', verbose_name='所属科目')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
