# Generated by Django 3.2.2 on 2024-07-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='base_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
