version: '3.8'

services:
  db:
    image: i5sbx7ps.mirror.aliyuncs.com/library/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "10086:8000"
    volumes:
      - static:/app/static
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - static:/static
    depends_on:
      - app
    ports:
      - "80:80"
volumes:
  db-data:
  static:
